BookStore(Web)_LC/BookStore(Web)/Controllers/AbsenceMISController.cs
using BookStore_Web_.Models;
using BookStore_Web_.Models.VM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace BookStore_Web_.Controllers
{
    public class AbsenceMISController : Controller
    {
        //只有資訊部 總經理可以進來
        BookStoreObject_Entities db = new BookStoreObject_Entities();
        Repository<Absence_Table> absenceTableRepository = null;
        Repository<Absence_Type> absenceTypeRepository = null;
        IEnumerable<BookStore_Web_.Models.Absence_Table> absenceTable = null;
        int EmpID = HomeController.EmpID = 3;
        int EmpOccu;
        public AbsenceMISController()
        {
            absenceTableRepository = new Repository<Absence_Table>(new BookStoreObject_Entities());
            absenceTypeRepository = new Repository<Absence_Type>(new BookStoreObject_Entities());
            absenceTable = absenceTableRepository.GetAll();
            EmpOccu = db.Emp_Information.Where(p => p.EmployeeID == EmpID).Select(p => p.Emp_OccupationID).FirstOrDefault();
        }
        
        public ActionResult MIS(int? page)
        {
            ViewBag.SortAbsenceTableNo = "AbsenceTableNo";
            ViewBag.SortAbsenceTableNoDesc = "AbsenceTableNodesc";
            ViewBag.SortAbsence_Type = "Absence_Type";
            ViewBag.SortAbsence_TypeDesc = "Absence_Typedesc";
            ViewBag.SortStartDate = "StartDate";
            ViewBag.SortStartDateDesc = "StartDatedesc";
            ViewBag.SortStatus = "Status";
            ViewBag.SortStatusDesc = "Statusdesc";
            
            absenceTable = MIS_Dept_Occu();
            return View(absenceTable.ToPagedList(page ?? 1, 5));
        }

        public ActionResult MISPager(int? page, int Dept=0, int Occu=0)
        {
            absenceTable = MIS_Dept_Occu(Dept, Occu);

            page = SetPage(page, absenceTable.Count());
            return PartialView(absenceTable.ToPagedList(page ?? 1, 5));
        }

        int? SetPage(int? page = 1, int data = 0)
        {
            if (data == 0)
                return page = 1;
            else if (data / 5 < page && data % 5 == 0)
                return page = data / 5;
            else if (data / 5 < page && data % 5 > 0)
                return page = data / 5 + 1;
            else
                return page;
        }

        IEnumerable<Absence_Table> MIS_Dept_Occu(int Dept = 0, int Occu = 0)
        {
            if (Dept != 0 && Occu != 0)
                absenceTable = absenceTable.Where(p => p.Emp_Information.Emp_DeptID == Dept && p.Emp_Information.Emp_OccupationID == Occu).ToList();
            else if (Dept != 0 && Occu == 0)
                absenceTable = absenceTable.Where(p => p.Emp_Information.Emp_DeptID == Dept).ToList();
            else if (Occu != 0 && Dept == 0)
                absenceTable = absenceTable.Where(p => p.Emp_Information.Emp_OccupationID == Occu).ToList();
            else
                absenceTable = absenceTable.ToList();

            return absenceTable;
        }

        //[ChildActionOnly]
        public ActionResult MISPartial(int? page, string sortBy, int Dept=0, int Occu=0)
        {
            #region for sortBy
            switch (sortBy)
            {
                case "AbsenceTableNo":
                    absenceTable = absenceTable.OrderBy(p => p.Absence_No);
                    break;
                case "AbsenceTableNodesc":
                    absenceTable = absenceTable.OrderByDescending(p => p.Absence_No);
                    break;
                case "Absence_Type":
                    absenceTable = absenceTable.OrderBy(p => p.Absence_Type.Absence_Type1);
                    break;
                case "Absence_Typedesc":
                    absenceTable = absenceTable.OrderByDescending(p => p.Absence_Type.Absence_Type1);
                    break;
                case "StartDate":
                    absenceTable = absenceTable.OrderBy(p => p.StartDate.Date);
                    break;
                case "StartDatedesc":
                    absenceTable = absenceTable.OrderByDescending(p => p.StartDate.Date);
                    break;
                case "Status":
                    absenceTable = absenceTable.OrderBy(p => p.ChechStatus.Status);
                    break;
                case "Statusdesc":
                    absenceTable = absenceTable.OrderByDescending(p => p.ChechStatus.Status);
                    break;
                default:
                    absenceTable = absenceTable.OrderBy(p => p.Absence_No);
                    break;
            }
            #endregion
            
            absenceTable = MIS_Dept_Occu(Dept, Occu);
            page = SetPage(page, absenceTable.Count());

            return PartialView(absenceTable.ToPagedList(page ?? 1, 5));
        }

        public ActionResult Dept()
        {
            var dept = db.Dept_Information.Select(p => new
            {
                DeptID = p.Emp_DeptID,
                DeptName = p.Dept_Name
            });
            return Json(dept.ToList(), JsonRequestBehavior.AllowGet);

        }

        public ActionResult Occu()
        {
            var occu = db.Emp_Occupation.Select(p => new
            {
                OccuID = p.Emp_OccupationID,
                OccuName = p.Emp_OccupationName
            });
            return Json(occu.ToList(), JsonRequestBehavior.AllowGet);

        }               

        public ActionResult Delete(int id)
        {
            var delete = absenceTableRepository.GetByID(id);
            delete.Dispose = true;
            absenceTableRepository.Update(delete);
            return RedirectToAction("MIS");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            ViewBag.AbsenceType = new SelectList(absenceTypeRepository.GetAll().ToList(), "Absence_ID", "Absence_Type1");
            var editAbsence = absenceTableRepository.GetByID(id);
            
            return View(editAbsence);
        }

        [HttpPost]
        public ActionResult Edit(Absence_Table _absenceTable)
        {            
            Absence_Table ab = absenceTableRepository.GetByID(_absenceTable.Absence_No);
            ab.Absence_ID = _absenceTable.Absence_ID;
            ab.StartDate = _absenceTable.StartDate;
            ab.EndDate = _absenceTable.EndDate;
            ab.Reason = _absenceTable.Reason;
            ab.Check_ID = 1;
            HttpPostedFileBase file = Request.Files["CertificateDoc"];
            if(file.ContentLength>0)
            {
                var imgSize = file.ContentLength;
                byte[] imgByte = new Byte[imgSize];
                file.InputStream.Read(imgByte, 0, imgSize);
                ab.Certificate_Doc = imgByte;
            }
            absenceTableRepository.Update(ab);
            return RedirectToAction("MIS");
        }

        public ActionResult GetImage(int id)
        {
            Absence_Table certificate_Doc = absenceTableRepository.GetByID(id);
            byte[] img = certificate_Doc.Certificate_Doc;
            if (img == null)
                return File(@"~\Content\AbsenceImage\oppos.jpg", "image/jpeg");
            else
                return new FileContentResult(img, "image/jpeg");
           
        }

        public ActionResult Accept(int id)
        {
            var accept = absenceTableRepository.GetByID(id);
            accept.Check_ID = 2;
            absenceTableRepository.Update(accept);
            //TODO 修改成功 頁面

            return RedirectToAction("MIS");
        }
        public ActionResult Reject(int id)
        {
            var accept = absenceTableRepository.GetByID(id);
            accept.Check_ID = 3;
            absenceTableRepository.Update(accept);

            return RedirectToAction("MIS");
        }
    }
}

BookStore(Web)_LC/BookStore(Web)/Views/AbsenceMIS/Edit.cshtml
@model BookStore_Web_.Models.Absence_Table
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminPage.cshtml";
}
<style>
    .thumb {
        width: 120px;
        height: 90px;
        border: solid 1px black;
    }
</style>
<h2>修改請假單</h2>
<div class="container body-content">
    @using (Html.BeginForm("Edit", "AbsenceMIS", FormMethod.Post, new { @class = "form-horizontal", @id = "Addform", encType = "multipart/form-data" }))
    {
        <div class="form-group">
            @Html.LabelFor(p => p.EmployeeID, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                <input type="text" class="form-control" value="@Model.Emp_Information.Emp_Name" readonly />
                <input type="hidden" id="EmployeeID" name="EmployeeID" class="form-control" value="@Model.EmployeeID" />
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.Absence_No, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                <input type="text" id="Absence_No" name="Absence_No" class="form-control" value="@Model.Absence_No" readonly />
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.Check_ID, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                <input type="text" class="form-control" value="@Model.ChechStatus.Status" readonly />
                <input type="hidden" id="Check_ID" name="Check_ID" value="@Model.Check_ID" />
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.Absence_ID, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.DropDownListFor(p => p.Absence_ID, (SelectList)ViewBag.AbsenceType, "--請選擇--", new { @class = "form-control", @value = @Model.Absence_ID })
                @Html.ValidationMessageFor(p => p.Absence_ID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.StartDate, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                <input type="datetime" id="StartDate" name="StartDate" class="form-control" value="@Model.StartDate" />
                <div hidden id="StartDatetime-error" class="text-danger">請填寫請假起始時間</div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.EndDate, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                <input type="datetime" id="EndDate" name="EndDate" class="form-control" value="@Model.EndDate" />
                <div hidden id="EndDatetime-error" class="text-danger">請填寫請假結束時間</div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.Reason, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.EditorFor(p => p.Reason, new { htmlAttributes = new { @class = "form-control", placeholder = "字數不得超過300" } })
                @Html.ValidationMessageFor(p => p.Reason, "", new { @class = "text-danger" })
            </div>

        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.Certificate_Doc, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                <div class="form-group">
                    <image alt="AbsenceTable image" title="AbsenceImage" class="form-control thumb" src="@Url.Action("GetImage", new { id = @Model.Absence_No })"></image>
                    <p>(原始證明)</p>
                </div>
                <input type="file" name="CertificateDoc" id="CertificateDoc" value="img" accept="image/x-png, image/gif, image/jpeg, image/jpg" />
                <input type="hidden" class="form-control" name="Certificate_Doc_ErrorMessage" id="Certificate_Doc_ErrorMessage" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" class="btn btn-default" id="Addbtn" value="修改" />
                <a href="@Url.Action("MIS","AbsenceMIS")" class="btn btn-default">回上一頁</a>
            </div>
        </div>
    }
</div>
<script>
    var startDate = $('#StartDate');
    var endDate = $('#EndDate');
    var startDateError = $('#StartDatetime-error');
    var endDateError = $('#EndDatetime-error');
    function checkDateTime() {

        if (startDate.val() === "") {
            startDateError.text("請填寫請假起始時間!!");
            startDateError.show()
            return false;
        }
        else
            startDateError.hide();

        if (endDate.val() === "") {
            endDateError.text("請填寫請假結束時間!!");
            endDateError.show();
            return false;
        }
        else
            endDateError.hide();

        if (startDate.val() >= endDate.val()) {
            startDateError.text("請假起始時間不可晚於或等於結束時間!!");
            startDateError.show();
            return false;
        }
        else
            return true;
    }


    $('#Addbtn').on('click', function (e) {
        if (checkDateTime())            
            $('#Addform').submit();  
        else
            return false;
    })
</script>
<script src="~/Scripts/jquery-2.2.0.min.js"></script>

BookStore(Web)_LC/BookStore(Web)/Views/AbsenceMIS/MIS.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<BookStore_Web_.Models.Absence_Table>
@{
    ViewBag.Title = "MIS";
    Layout = "~/Views/Shared/AdminPage.cshtml";
}

<style>
    .thumb {
        width: 120px;
        height: 90px;
        border: solid 1px black;
    }
</style>
<link href="~/Content/PagedList.css" rel="stylesheet" />

<h2>請假單查詢(網管人員專用頁面)</h2>
<div>
    <label>篩選:</label>
    <select id="sel1"></select>
    <select id="sel2"></select>
</div>
<div>
    <label>排序:</label>
    <select id="sel3">
        <option value="@ViewBag.SortAbsenceTableNo">@Html.DisplayNameFor(model => model.First().Absence_No).ToHtmlString() (正)</option>
        <option value="@ViewBag.SortAbsenceTableNoDesc">@Html.DisplayNameFor(model => model.First().Absence_No).ToHtmlString() (逆)</option>
        <option value="@ViewBag.SortAbsence_Type">@Html.DisplayNameFor(model => model.First().Absence_Type.Absence_Type1).ToHtmlString() (正)</option>
        <option value="@ViewBag.SortAbsence_TypeDesc">@Html.DisplayNameFor(model => model.First().Absence_Type.Absence_Type1).ToHtmlString() (逆)</option>
        <option value="@ViewBag.SortStartDate">@Html.DisplayNameFor(model => model.First().StartDate).ToHtmlString() (正)</option>
        <option value="@ViewBag.SortStartDateDesc">@Html.DisplayNameFor(model => model.First().StartDate).ToHtmlString() (逆)</option>
        <option value="@ViewBag.SortStatus">@Html.DisplayNameFor(model => model.First().ChechStatus.Status).ToHtmlString() (正)</option>
        <option value="@ViewBag.SortStatusDesc">@Html.DisplayNameFor(model => model.First().ChechStatus.Status).ToHtmlString() (逆)</option>
    </select>
</div>

<div></div>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.First().Absence_No).ToHtmlString()</th>
            <th>@Html.DisplayNameFor(model => model.First().Emp_Information.Emp_Name).ToHtmlString()</th>
            <th>@Html.DisplayNameFor(model => model.First().Emp_Information.Emp_DeptID).ToHtmlString()</th>
            <th>@Html.DisplayNameFor(model => model.First().Absence_Type.Absence_Type1).ToHtmlString()</th>
            <th>@Html.DisplayNameFor(model => model.First().StartDate).ToHtmlString()</th>
            <th>@Html.DisplayNameFor(model => model.First().EndDate).ToHtmlString()</th>
            <th>@Html.DisplayNameFor(model => model.First().Reason).ToHtmlString()</th>
            <th>@Html.DisplayNameFor(model => model.First().Certificate_Doc)</th>
            <th>@Html.DisplayNameFor(model => model.First().ChechStatus.Status).ToHtmlString()</th>
            <th>接受</th>
            <th>拒絕</th>
            <th>編輯</th>
            <th>刪除</th>
        </tr>
    </thead>
    <tbody id="div1"></tbody>
</table>
<div id="mypager">
    @Html.PagedListPager(Model, page => "#",
                     PagedListRenderOptions.PageNumbersOnly)
</div>


<script>

    var sel = $('#sel1');
    sel.on('change', function () { selload($('#mypager').children().children().children(".active").children('a').text()); })
    var sel2 = $('#sel2');
    sel2.on('change', function () { selload($('#mypager').children().children().children(".active").children('a').text()); })
    var sel3 = $('#sel3');
    sel3.on('change', function () { selload($('#mypager').children().children().children(".active").children('a').text()); })
    var div = $('#div1');
    var pager = $('#mypager');
    pager.on('click','a', function () { selload($(this).text()); })
    $.getJSON('@Url.Action("Dept","AbsenceMIS")', {}, function (datas) {
        var opt = new Option("--所有部門--", 0);
        sel.append(opt);
        $.each(datas, function (i,Dept) {
            var opt = new Option(Dept.DeptName, Dept.DeptID);
            sel.append(opt);
        });
    });
    $.getJSON('@Url.Action("Occu","AbsenceMIS")', {}, function (datas) {
        var opt = new Option("--所有職位--", 0);
        sel2.append(opt);
        $.each(datas, function (i, Occu) {
            var opt = new Option(Occu.OccuName, Occu.OccuID);
            sel2.append(opt);
        });
    });
    selload();
    function selload(e) {
        div.load('/AbsenceMIS/MISPartial?Dept=' + sel.val() + '&Occu=' + sel2.val() + '&sortBy=' + sel3.val() + '&page=' + e);
        pager.load('/AbsenceMIS/MISPager?Dept=' + sel.val() + '&Occu=' + sel2.val() + '&sortBy=' + sel3.val() + '&page=' + e);
    }    
</script>
<script src="~/Scripts/jquery-2.2.0.min.js"></script>

BookStore(Web)_LC/BookStore(Web)/Views/AbsenceMIS/MISPager.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<BookStore_Web_.Models.Absence_Table>
@{
    ViewBag.Title = "MISPager";
}
@Html.PagedListPager(Model, page => "#",
                     PagedListRenderOptions.PageNumbersOnly)

BookStore(Web)_LC/BookStore(Web)/Views/AbsenceMIS/MISPartial.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<BookStore_Web_.Models.Absence_Table>
@{
    ViewBag.Title = "MISPartial";
}
<table class="table table-bordered table-hover">
    <tbody>
        @*Model是一個保留字，代表Controller傳過來的資料*@
        @*但是Model是什麼類型的資料，我們不知道?如果要知道Model是什麼類型的資料，要看最上面的宣告*@
        @foreach (var _Absence in Model)
        {
            <tr>
                <td>@Html.DisplayFor(model => _Absence.Absence_No)</td>
                <td>@Html.DisplayFor(model => _Absence.Emp_Information.Emp_Name)</td>
                <td>@Html.DisplayFor(model => _Absence.Emp_Information.Dept_Information.Dept_Name)</td>
                <td>@Html.DisplayFor(p => _Absence.Absence_Type.Absence_Type1)</td>
                <td>@Html.DisplayFor(p => _Absence.StartDate)</td>
                <td>@Html.DisplayFor(p => _Absence.EndDate)</td>
                <td>@Html.DisplayFor(p => _Absence.Reason)</td>
                <td><image alt="AbsenceTable image" title="AbsenceImage" class="thumb" src="@Url.Action("GetImage", new { id = _Absence.Absence_No })"></image></td>
                <td>@Html.DisplayFor(p => _Absence.ChechStatus.Status)</td>
                <td><a href="/AbsenceMIS/Accept/@_Absence.Absence_No" class="btn btn-warning">接受</a></td>
                <td><a href="/AbsenceMIS/Reject/@_Absence.Absence_No" class="btn btn-danger">拒絕</a></td>
                <td><a href="/AbsenceMIS/Edit/@_Absence.Absence_No" class="btn btn-warning">編輯</a></td>
                <td><a href="/AbsenceMIS/Delete/@_Absence.Absence_No" class="btn btn-danger">刪除</a></td>
            </tr>
        }
    </tbody>
</table>